name: CI/CD íŒŒì´í”„ë¼ì¸ (moneybuddy-server)

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: ì½”ë“œ ì²´í¬ì•„ì›ƒ
        uses: actions/checkout@v4

      - name: ìë°” 17 ì„¤ì •
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: NestJS ë¹Œë“œ
        run: npm run build

      - name: ë„ì»¤ ì´ë¯¸ì§€ ë¹Œë“œ
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/moneybuddy-server .

      - name: ë„ì»¤ í—ˆë¸Œ ë¡œê·¸ì¸
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: ë„ì»¤ í—ˆë¸Œì— ì´ë¯¸ì§€ í‘¸ì‹œ
        run: docker push ${{ secrets.DOCKER_USERNAME }}/moneybuddy-server

      - name: ì›ê²©ì„œë²„ì— ë°°í¬
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: ${{ secrets.REMOTE_PORT }}
          script: |
            cd ${{ secrets.REMOTE_PROJECT_PATH }}
            docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
            echo "${{secrets.ENV_FILE}}" > ./.env
            docker compose down
            docker rmi ${{ secrets.DOCKER_USERNAME }}/moneybuddy-server
            docker pull ${{ secrets.DOCKER_USERNAME }}/moneybuddy-server
            docker compose up -d --remove-orphans
            cd /home/gyubuntu/nginx-proxy
            docker compose down
            docker compose up -d

      - name: ì„±ê³µ ë©”ì„¸ì§€ ì¶œë ¥
        if: success()
        run: echo "ğŸ‰ CI/CD íŒŒì´í”„ë¼ì¸ ì„±ê³µ"
